import type { WebhookEvent } from '../schemas/webhook.js';

export type RavoxWebhookPayload<TData = unknown> = {
  event: WebhookEvent;
  instanceId?: string;
  organizationId: string;
  timestamp: string;
  data: TData;
};

export type SendMessageJob = {
  messageId: string;
  instanceId: string;
  organizationId: string;
  to: string;
  body?: string;
  type?: 'TEXT' | 'IMAGE' | 'AUDIO' | 'DOCUMENT' | 'VIDEO';
  media?: {
    path: string;
    mimeType: string;
    fileName: string;
  };
};

export type ConnectInstanceJob = {
  instanceId: string;
  organizationId: string;
  clearSession?: boolean;
};

export type WhatsAppOperationType =
  | 'MESSAGE_SEND_LOCATION'
  | 'MESSAGE_SEND_CONTACT'
  | 'MESSAGE_SEND_CONTACTS'
  | 'MESSAGE_SEND_STICKER'
  | 'MESSAGE_SEND_GIF'
  | 'MESSAGE_SEND_LINK'
  | 'MESSAGE_SEND_REACTION'
  | 'MESSAGE_REMOVE_REACTION'
  | 'MESSAGE_SEND_POLL'
  | 'MESSAGE_SEND_POLL_VOTE'
  | 'MESSAGE_REPLY'
  | 'MESSAGE_FORWARD'
  | 'MESSAGE_DELETE'
  | 'MESSAGE_READ'
  | 'MESSAGE_PIN'
  | 'MESSAGE_SEND_PTV'
  | 'CONTACT_CHECK'
  | 'CONTACT_CHECK_BATCH'
  | 'CONTACT_METADATA'
  | 'CONTACT_PROFILE_PICTURE'
  | 'CONTACT_ADD'
  | 'CONTACT_REMOVE'
  | 'CONTACT_BLOCK'
  | 'CONTACT_UNBLOCK'
  | 'CONTACT_REPORT'
  | 'PRIVACY_GET'
  | 'PRIVACY_LAST_SEEN'
  | 'PRIVACY_ONLINE'
  | 'PRIVACY_PROFILE_PICTURE'
  | 'PRIVACY_STATUS'
  | 'PRIVACY_READ_RECEIPTS'
  | 'PRIVACY_GROUP_ADD'
  | 'PRIVACY_DEFAULT_DISAPPEARING'
  | 'PRIVACY_BLOCKLIST'
  | 'INSTANCE_ME'
  | 'INSTANCE_DEVICE'
  | 'INSTANCE_PAIRING_CODE'
  | 'INSTANCE_PROFILE_NAME'
  | 'INSTANCE_PROFILE_DESCRIPTION'
  | 'INSTANCE_PROFILE_PICTURE'
  | 'INSTANCE_PROFILE_PICTURE_REMOVE'
  | 'STATUS_SEND_TEXT'
  | 'STATUS_SEND_IMAGE'
  | 'STATUS_SEND_VIDEO'
  | 'STATUS_REPLY_TEXT'
  | 'STATUS_REPLY_STICKER'
  | 'STATUS_REPLY_GIF'
  | 'COMMUNITY_SYNC'
  | 'COMMUNITY_CREATE'
  | 'COMMUNITY_METADATA'
  | 'COMMUNITY_UPDATE_NAME'
  | 'COMMUNITY_UPDATE_DESCRIPTION'
  | 'COMMUNITY_SETTINGS_UPDATE'
  | 'COMMUNITY_PARTICIPANTS_ADD'
  | 'COMMUNITY_PARTICIPANTS_REMOVE'
  | 'COMMUNITY_ADMINS_PROMOTE'
  | 'COMMUNITY_ADMINS_DEMOTE'
  | 'COMMUNITY_GROUPS_LINK'
  | 'COMMUNITY_GROUPS_UNLINK'
  | 'COMMUNITY_GET_INVITE_LINK'
  | 'COMMUNITY_REVOKE_INVITE_LINK'
  | 'COMMUNITY_ACCEPT_INVITE'
  | 'NEWSLETTER_CREATE'
  | 'NEWSLETTER_LIST'
  | 'NEWSLETTER_SEARCH'
  | 'NEWSLETTER_METADATA'
  | 'NEWSLETTER_FOLLOW'
  | 'NEWSLETTER_UNFOLLOW'
  | 'NEWSLETTER_MUTE'
  | 'NEWSLETTER_UNMUTE'
  | 'NEWSLETTER_UPDATE_NAME'
  | 'NEWSLETTER_UPDATE_DESCRIPTION'
  | 'NEWSLETTER_UPDATE_PICTURE'
  | 'NEWSLETTER_DELETE'
  | 'NEWSLETTER_ACCEPT_ADMIN_INVITE'
  | 'NEWSLETTER_REVOKE_ADMIN_INVITE'
  | 'NEWSLETTER_REMOVE_ADMIN'
  | 'NEWSLETTER_TRANSFER_OWNERSHIP'
  | 'NEWSLETTER_REACT_MESSAGE'
  | 'NEWSLETTER_FETCH_MESSAGES'
  | 'BUSINESS_PROFILE'
  | 'BUSINESS_PROFILE_UPDATE'
  | 'BUSINESS_PRODUCTS_LIST'
  | 'BUSINESS_PRODUCT_GET'
  | 'BUSINESS_PRODUCT_CREATE'
  | 'BUSINESS_PRODUCT_UPDATE'
  | 'BUSINESS_PRODUCT_DELETE'
  | 'BUSINESS_COLLECTIONS_LIST'
  | 'BUSINESS_TAGS_CREATE'
  | 'BUSINESS_TAGS_UPDATE'
  | 'BUSINESS_TAGS_DELETE'
  | 'BUSINESS_TAGS_CHAT_ADD'
  | 'BUSINESS_TAGS_CHAT_REMOVE'
  | 'GROUP_SYNC'
  | 'GROUP_CREATE'
  | 'GROUP_METADATA_SYNC'
  | 'GROUP_UPDATE_NAME'
  | 'GROUP_UPDATE_DESCRIPTION'
  | 'GROUP_UPDATE_PHOTO'
  | 'GROUP_PARTICIPANTS_ADD'
  | 'GROUP_PARTICIPANTS_REMOVE'
  | 'GROUP_REQUESTS_LIST'
  | 'GROUP_REQUESTS_APPROVE'
  | 'GROUP_REQUESTS_REJECT'
  | 'GROUP_ADMINS_PROMOTE'
  | 'GROUP_ADMINS_DEMOTE'
  | 'GROUP_MENTION'
  | 'GROUP_MENTION_ALL'
  | 'GROUP_MENTION_GROUP'
  | 'GROUP_SETTINGS_UPDATE'
  | 'GROUP_LEAVE'
  | 'GROUP_GET_INVITE_LINK'
  | 'GROUP_REVOKE_INVITE_LINK'
  | 'GROUP_ACCEPT_INVITE'
  | 'GROUP_INVITE_METADATA'
  | 'CHAT_READ'
  | 'CHAT_ARCHIVE'
  | 'CHAT_PIN'
  | 'CHAT_MUTE'
  | 'CHAT_CLEAR'
  | 'CHAT_DELETE'
  | 'CHAT_EPHEMERAL';

export type WhatsAppOperationJob = {
  operationId: string;
  instanceId: string;
  organizationId: string;
};

export type DispatchWebhookJob = {
  deliveryId: string;
  webhookId: string;
  payload: RavoxWebhookPayload;
};
